/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

/**
 *
 * @author Joaop
 */
public class CadastrarProduto extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarProduto
     */
    public CadastrarProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLivros = new javax.swing.JButton();
        btnFilmes = new javax.swing.JButton();
        btnPerifericos = new javax.swing.JButton();
        bntCelulares = new javax.swing.JButton();
        btnComputadores = new javax.swing.JButton();
        btnEletroeletronicos = new javax.swing.JButton();
        btnVestuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnLivros.setText("Livros");
        btnLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLivrosActionPerformed(evt);
            }
        });

        btnFilmes.setText("Filmes");
        btnFilmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilmesActionPerformed(evt);
            }
        });

        btnPerifericos.setText("Periféricos");
        btnPerifericos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerifericosActionPerformed(evt);
            }
        });

        bntCelulares.setText("Celulares");
        bntCelulares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCelularesActionPerformed(evt);
            }
        });

        btnComputadores.setText("Computadores");
        btnComputadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComputadoresActionPerformed(evt);
            }
        });

        btnEletroeletronicos.setText("Eletroeletrônicos");
        btnEletroeletronicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEletroeletronicosActionPerformed(evt);
            }
        });

        btnVestuario.setText("Vestuário");
        btnVestuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVestuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(btnLivros)
                        .addGap(32, 32, 32)
                        .addComponent(btnFilmes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPerifericos))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bntCelulares)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnComputadores)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEletroeletronicos)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVestuario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(121, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLivros)
                    .addComponent(btnFilmes)
                    .addComponent(btnPerifericos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntCelulares)
                    .addComponent(btnComputadores)
                    .addComponent(btnEletroeletronicos)
                    .addComponent(btnVestuario))
                .addGap(122, 122, 122))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFilmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilmesActionPerformed
        new TelaCadastraProduto("filmes").setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnFilmesActionPerformed

    private void btnLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLivrosActionPerformed
        new TelaCadastraProduto("livros").setVisible(true);
        //this.setVisible(false);
        
    }//GEN-LAST:event_btnLivrosActionPerformed

    private void btnPerifericosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerifericosActionPerformed
        new TelaCadastraProduto("perifericos").setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnPerifericosActionPerformed

    private void bntCelularesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCelularesActionPerformed
        new TelaCadastraProduto("celulares").setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bntCelularesActionPerformed

    private void btnComputadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComputadoresActionPerformed
        new TelaCadastraProduto("computadores").setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnComputadoresActionPerformed

    private void btnEletroeletronicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEletroeletronicosActionPerformed
        new TelaCadastraProduto("eletroeletronicos").setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEletroeletronicosActionPerformed

    private void btnVestuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVestuarioActionPerformed
        new TelaCadastraProduto("vestuario").setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVestuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntCelulares;
    private javax.swing.JButton btnComputadores;
    private javax.swing.JButton btnEletroeletronicos;
    private javax.swing.JButton btnFilmes;
    private javax.swing.JButton btnLivros;
    private javax.swing.JButton btnPerifericos;
    private javax.swing.JButton btnVestuario;
    // End of variables declaration//GEN-END:variables
}
